# Generated by Django 4.2.4 on 2023-08-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("url", models.TextField()),
                ("short_description", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField()),
                ("reviews", models.IntegerField()),
                ("developer_url", models.TextField()),
                ("pricing", models.TextField(blank=True, null=True)),
                ("launched", models.DateField(blank=True, null=True)),
                ("languages", models.TextField(blank=True, null=True)),
                ("works_with", models.TextField(blank=True, null=True)),
                ("review_summary", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Developer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("url", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("number_of_apps", models.IntegerField()),
                ("average_rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("country", models.TextField(blank=True, null=True)),
                ("time_used", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("rating", models.FloatField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("replied_date", models.DateField(blank=True, null=True)),
                ("replied_comment", models.TextField(blank=True, null=True)),
                ("app", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shopify.app")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("url", models.TextField()),
                ("featured_apps", models.ManyToManyField(blank=True, to="shopify.app")),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="shopify.category"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="app",
            name="categories",
            field=models.ManyToManyField(to="shopify.category"),
        ),
        migrations.AddField(
            model_name="app",
            name="developer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shopify.developer"),
        ),
    ]
